version: "3.7"

networks:
    app-network:
        driver: bridge
volumes:
    mysqldata:
        driver: local

services:
    #Laravel App
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: hakase-labs/laravel
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network

    #Nginx Service
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8100:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./nginx:/etc/nginx/conf.d/
        networks:
            - app-network

    #MySQL Service
    db:
        image: mysql:5.7
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - mysqldata:/var/lib/mysql/
        networks:
            - app-network
